version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.springdoc:*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.spockframework:*"
        update-types:
          - "version-update:semver-major"
